name: Build Alpha Release

on:
   push:
      branches:
         - alpha

env:
   FRL_GITHUB_RUNNER_USERNAME: GitHub Runner
   FRL_GITHUB_RUNNER_USEREMAIL: github@frostland.fr

jobs:
   bump-version-and-tag:
      name: Bump Build Version and Tag
      runs-on: [macos-10.15]
      
      steps:
         # Note: We use brew cask install because GitHub’s runner is
         #       a bit late on homebrew’s version
         - name: Install hagvtool
           run: brew cask install happn-tech/public/hagvtool
         
         - name: Select Xcode 11.7 for Next Steps
           run: sudo xcode-select -s "/Applications/Xcode_11.7.app"
         
         - name: Setup Runner’s git Username and Email
           run: |
              git config --global user.name  "$FRL_GITHUB_RUNNER_USERNAME"
              git config --global user.email "$FRL_GITHUB_RUNNER_USEREMAIL"
         
         - name: Checkout GPS Stone versioning
           uses: actions/checkout@v2
           with:
              ref: "versioning"
         
         - name: Bump Build Version in versioning Branch
           run: |
              set -euo pipefail
              
              BUILD_VERSION_FILE=build_number_gpsstone.txt
              echo $(($(cat "$BUILD_VERSION_FILE") + 1)) >"$BUILD_VERSION_FILE"
              git commit "$BUILD_VERSION_FILE" -m "Bump build version"
              # Note: This might fail if someone pushed a version from another
              # branch. We do not auto-retry for now because this won’t happen
              # for this repository.
              git push
              
              cp "$BUILD_VERSION_FILE" ../new_build_version
         
         - name: Checkout GPS Stone
           uses: actions/checkout@v2
         
         - name: Bump Build Version
           run: |
              set -euo pipefail
              
              NEW_VERSION="$(cat ../new_build_version)"
              TAG_NAME="GPS_Stone-${NEW_VERSION}a"
              rm -f ../new_build_version
              
              hagvtool set-build-version "$NEW_VERSION"
              
              git commit -am "Bump build version to $NEW_VERSION with hagvtool"
              git tag "$TAG_NAME"
              git push origin "$TAG_NAME"
