name: Prepare Alpha Release

on:
   push:
      branches:
         - alpha

env:
   FRL_GITHUB_RUNNER_USERNAME: GitHub Runner (GPS Stone)
   FRL_GITHUB_RUNNER_USEREMAIL: github@frostland.fr

jobs:
   bump-version-and-tag:
      name: Bump Build Version and Tag
      runs-on: [macos-10.15]
      
      steps:
         - name: Install hagvtool
           # If brew is not up-to-date, brew cask install is not used automatically
           run: brew install happn-tech/public/hagvtool || brew cask install happn-tech/public/hagvtool
         
         - name: Setup Runner’s git Username and Email
           run: |
              git config --global user.name  "$FRL_GITHUB_RUNNER_USERNAME"
              git config --global user.email "$FRL_GITHUB_RUNNER_USEREMAIL"
         
         - name: Import GPG Signing Key
           run: gpg --import --pinentry-mode=loopback --passphrase '' <<<'${{ secrets.GPG_PRIVATE_KEY }}'
         
         - name: Checkout GPS Stone versioning
           uses: actions/checkout@v2
           with:
              ref: "versioning"
         
         - name: Bump Build Version in versioning Branch
           run: |
              set -euo pipefail
              
              BUILD_VERSION_FILE=build_number_gpsstone.txt
              echo $(($(cat "$BUILD_VERSION_FILE") + 1)) >"$BUILD_VERSION_FILE"
              git commit "$BUILD_VERSION_FILE" -m "Bump build version"
              # Note: This might fail if someone pushed a version from another
              # branch. We do not auto-retry for now because this won’t happen
              # for this repository.
              git push
              
              cp "$BUILD_VERSION_FILE" ../new_build_version
         
         - name: Checkout GPS Stone
           uses: actions/checkout@v2
         
         - name: Bump Build Version
           run: |
              set -euo pipefail
              
              NEW_VERSION="$(cat ../new_build_version)"
              TAG_NAME="GPS_Stone-${NEW_VERSION}a"
              rm -f ../new_build_version
              
              hagvtool set-build-version "$NEW_VERSION"
              
              git commit --allow-empty -am "Bump build version to $NEW_VERSION with hagvtool"
              git tag -sm "GPS Stone $NEW_VERSION (alpha)" "$TAG_NAME"
              git push origin "$TAG_NAME"
