name: Build Alpha Release

on:
   push:
      branches:
         - alpha

env: {}

jobs:
   bump-version-and-tag:
      name: Bump Build Version and Tag
      runs-on: [macos-10.15]
      
      steps:
         - name: Checkout hagvtool
           uses: actions/checkout@v2
           with:
              repository: "happn-tech/XcodeTools"
              ref: "0.2.1"
         
         - name: Build and Install hagvtool
           run: |
              set -euo pipefail
              
              sudo xcode-select -s "/Applications/Xcode_12.app"
              xcodebuild build \
                 -workspace XcodeTools.xcworkspace -scheme hagvtool \
                 -configuration Release -sdk macosx \
                 -disableAutomaticPackageResolution \
                 -derivedDataPath ../buildData
              cp ../buildData/Build/Products/Release/hagvtool /usr/local/bin/hagvtool
              rm -fr ../buildData
         
         - name: Select Xcode 11.7 for Next Steps
           run: sudo xcode-select -s "/Applications/Xcode_11.7.app"
         
         - name: Checkout GPS Stone versioning
           uses: actions/checkout@v2
           with:
              ref: "versioning"
         
         - name: Bump Build Version in versioning Branch
           run: |
              set -euo pipefail
              
              BUILD_VERSION_FILE=build_number_gpsstone.txt
              echo $(($(cat "$BUILD_VERSION_FILE") + 1)) >"$BUILD_VERSION_FILE"
              git commit -a --amend --no-edit
              git push -f
              
              cp "$BUILD_VERSION_FILE" ../new_build_version
         
         - name: Checkout GPS Stone
           uses: actions/checkout@v2
         
         - name: Bump Build Version
           run: |
              set -euo pipefail
              
              NEW_VERSION="$(cat ../new_build_version)"
              TAG_NAME="GPS_Stone-${NEW_VERSION}a"
              rm -f ../new_build_version
              
              hagvtool set-build-version "$NEW_VERSION"
              
              git commit -am "Bump build version to $NEW_VERSION with hagvtool"
              git tag "$TAG_NAME"
              git push origin "$TAG_NAME"
