name: Build Alpha Release

on:
   push:
      branches:
         - alpha

env: {}

jobs:
   build:
      name: Build
      runs-on: [macos-10.15]

      steps:
         # First we setup the Xcode we want
         - name: Select Xcode 11.7 to build
           run: sudo xcode-select -s "/Applications/Xcode_11.7.app"
