name: Create Preview Release Tag

on:
   push:
      branches:
         - develop

env:
   # FYI diff between author and committer: https://stackoverflow.com/a/18754896
   # For commits
   GIT_AUTHOR_EMAIL: github@frostland.fr
   GIT_AUTHOR_NAME: GitHub Runner (GPS Stone)
   # For tags
   GIT_COMMITTER_EMAIL: github@frostland.fr
   GIT_COMMITTER_NAME: GitHub Runner (GPS Stone)

jobs:
   bump-version-and-tag:
      name: Bump Build Version and Tag
      runs-on: [macos-10.15]
      
      steps:
         - name: Install hagvtool
           # If brew is not up-to-date, `brew install --cask` might not exist
           run: brew install --cask happn-tech/public/hagvtool || brew cask install happn-tech/public/hagvtool
         
         - name: Import GPG Signing Key
           run: gpg --import --pinentry-mode=loopback --passphrase '' <<<'${{ secrets.GPG_PRIVATE_KEY }}'
         
         - name: Checkout GPS Stone versioning
           uses: actions/checkout@v2
           with:
              ref: "versioning"
         
         - name: Bump Build Version in versioning Branch
           run: |
              set -euo pipefail
              
              BUILD_VERSION_FILE=build_number_gpsstone.txt
              echo $(($(cat "$BUILD_VERSION_FILE") + 1)) >"$BUILD_VERSION_FILE"
              git commit "$BUILD_VERSION_FILE" -m "Bump build version"
              # Note: This might fail if someone pushed a version from another
              # branch. We do not auto-retry for now because this won’t happen
              # for this repository.
              git push
              
              cp -f "$BUILD_VERSION_FILE" ../new_build_version
         
         - name: Checkout GPS Stone
           uses: actions/checkout@v2
         
         - name: Set Build Versions and Push Tag
           run: |
              set -euo pipefail
              
              NEW_BUILD_VERSION="$(cat ../new_build_version)"
              TAG_NAME="GPS_Stone/preview/$NEW_BUILD_VERSION"
              rm -f ../new_build_version
              
              hagvtool set-build-version "$NEW_BUILD_VERSION"
              
              git commit --allow-empty -am "Set build version to $NEW_BUILD_VERSION with hagvtool"
              git tag -sm "GPS Stone $NEW_BUILD_VERSION (preview release)" "$TAG_NAME"
              git push origin "$TAG_NAME"
